spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 123456
logging:
  level:
    root: info
    com.hzt: debug
  file:
    name: log/blog-pro.log
